### ISSUE TITLE
Uncaught TypeError: Cannot read property 'animate' of undefined

### ISSUE THREAD

**Issue by r1cht3r** [maykar/lovelace-swipe-navigation#13]
I recently installed this lovelace plugin but am receiving this error in the logs:
```
https://<redacted>/local/community/lovelace-swipe-navigation/swipe-navigation.js:12:22 Uncaught TypeError: Cannot read property 'animate' of undefined
```
Here's what I added from the docs:
location: `/www/community/lovelace-swipe-navigation/swipe-navigation.js`
lovelace config:
```
resources:
  - url: /local/community/lovelace-swipe-navigation/swipe-navigation.js
    type: js
```
Anything obvious I'm doing wrong? Thanks!

**Comment by maykar** [comment]
Try the latest release (1.2.1), should fix the issue.

**Comment by r1cht3r** [comment]
Same error upon installation of latest release 1.2.1, I fully restarted the HA service to make sure it wasn't something cached.

**Comment by maykar** [comment]
HA wouldn't be caching it. Your browser would be. Either clear your browsers cache or Ctrl+Shift+R

**Comment by maykar** [comment]
Also if you're using HACS your resource URL is wrong and would also cause caching issues. 
Should be:
```yaml
resources:
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js
```

If you're not using HACS you need to add to the version number at the end when you update
```yaml
resources:
  - url: /local/community/lovelace-swipe-navigation/swipe-navigation.js?v=1.2.1
    type: js
```

Then Ctrl+Shift+R or clear cache
