### ISSUE TITLE
Swipe not working if all tabs are hidden in custom header

### ISSUE THREAD

**Issue by acateon** [maykar/lovelace-swipe-navigation#22]
I'm trying to semi-hide the header with only using the options button for a clock. But as soon as I hide all the tabs from view the swipe function stops working. Is it possible to work around this setup to make it work?

```
custom_header:
  compact_mode: true
  header_css: 'background: transparent;'
  panel_view_css: 'padding-top: 80px;' # Same as view_css only when using panel view.
  indicator_top: true
  exceptions:
    - conditions:
        user: Kiosk
      config:
        compact_mode: true
        disable_sidebar: true
        header_css: 'background: transparent;'
        options_css: 'font-size: 12px;'
        panel_view_css: 'padding-top: 50px;' # Same as view_css only when using panel view.
        button_text:
          options: >-
            {{ hours24 }}:{{ minutesLZ }}
        menu_hide: true
        hidden_tab_redirect: false
        hide_tabs:
          - 0 to 5
```
