### ISSUE TITLE
Swipe navs not working with custom fields in custom:button-card

### ISSUE THREAD

**Issue by chertvl** [maykar/lovelace-swipe-navigation#57]
Hello, Maykar!
Firstly, sorry for my English.

All my front-end was builded with component "Custom Button Card", which allow to create cards inside itself.
I have some areas where I use cards inside custom buttons card,  and these custom fields does not supports swipe navigation. 

How to reproduce:
Use custom:button-card, create custom_field: with any card. For example, for adding graph to your existing card. Zone with graph will not pesponse to swipes.

Can I add this custom fields to allowlist somehow?

Thanks for your respond! 

Example from cutsom-button-card docs.
```
- type: custom:button-card
  aspect_ratio: 1/1
  custom_fields:
    graph:
      card:
        type: sensor
        entity: sensor.sensor1
        graph: line
  styles:
    custom_fields:
      graph:
        - filter: opacity(50%)
        - overflow: unset
    card:
      - overflow: unset
    grid:
      - grid-template-areas: '"i" "n" "graph"'
      - grid-template-columns: 1fr
      - grid-template-rows: 1fr min-content min-content

  entity: light.test_light
  hold_action:
    action: more-info
```
